osx_image: xcode8.3
sudo: required
dist: trusty
os:
  - osx
  - linux
addons:
  chrome: stable
  apt:
    packages:
            - libsecret-1-0
  artifacts:
    paths:
      - $(ls build/*.zip | tr "\n" ":")
language: node_js
node_js: "8"

cache:
  yarn: true
  directories:
    - node_modules
    - electron/node_modules
install:
  - yarn install
before_script:
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y wine1.8 gcc-multilib g++-multilib icnsutils graphicsmagick xz-utils
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - yarn run ci

notifications:
  email: false

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  only:
  - master
  - /^release\/v\d+\.\d+(\.\d+)?(-\S*)?$/
