sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "8"

install:
  - npm install
before_script:

  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y wine1.8 icnsutils graphicsmagick xz-utils gcc-multilib g++-multilib
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm run ci

notifications:
  email: false

branches:
  only:
  - gh-pages
  - /.*/
