sudo: required
os: osx
osx_image: xcode8.3
addons:
  chrome: stable
language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules
    - electron/node_modules
install:
  - yarn install
before_script:
  - brew install yarn
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - yarn run ci

notifications:
  email: false

branches:
  only:
  - gh-pages
  - /.*/
